### ISSUE TITLE
Artist not found and Album not found when browsing "Show artist" or "Show album"

### ISSUE THREAD

**Issue by surfacescan** [tkem/mopidy-local-sqlite#47]
For some reason when I try to see the Artist page from the context menu on the musicbox's default webclient (from wouter) I get a strange behaviour.

Not only does it say artist not found, but it seems that the angular or single page app is broken - instead of just

   http://192.168.0.138/#browse

I now get
   http://192.168.0.138/#artists?local:artist:md5:259c6b3c747416f3b5273566559b756c 

A little looking and I see that if I go the route of  browse->artist the code is: 

`<a href="#" onclick="return getBrowseDir(this.id);" id="local:artist:md5:259c6b3c747416f3b5273566559b756c" "=""><h1 class="trackname"><i class="fa fa-folder-o"></i> !!!</h1></a>`

However in the queue page with the show artist popup, the code is

`<a href="#" onclick="showArtist(&quot;local:artist:md5:259c6b3c747416f3b5273566559b756c&quot;);" class="popupArtistHref ui-link-inherit">Show Artist <span class="popupArtistName">!!!</span>
    </a>`

**Comment by tkem** [comment]
Without looking into the details, this looks more like an issue in woutervanwijk/Mopidy-MusicBox-Webclient to me..,

**Comment by tkem** [comment]
AFAICS there's already an issue for this: woutervanwijk/Mopidy-MusicBox-Webclient/issues/62
