### ISSUE TITLE
Logfile

### ISSUE THREAD

**Issue by surfacescan** [tkem/mopidy-local-sqlite#49]
Hi There - I find that sometimes a local scan will render the "browse->local folders" empty - and other times not.

I suspect that there are certain characters in a filename perhaps that are causing this.

Is there any kind of logging so I can see perhaps why some folders end of empty?

Thanks

**Comment by tkem** [comment]
Please have a look at the official Mopidy documentation: https://docs.mopidy.com/en/latest/troubleshooting/

**Comment by surfacescan** [comment]
OK.thought since yours was a plugin it might have its own debugging, but
seems its piped through Mopidy. Will check there.

Any hints on why certain files or characters in a file might prevent folder
contents from being shown?  Or is that at Mopidy level, not sql-lite?

Thanks

**Comment by tkem** [comment]
Unless you can confirm that it's really the file name characters that cause
this, e.g. by finding corresponding error messages in the log file, I won't
speculate on this.
