### ISSUE TITLE
Stop using Mopidy internal APIs

### ISSUE THREAD

**Issue by tkem** [tkem/mopidy-local-sqlite#59]
See mopidy/mopidy#1173

**Comment by jodal** [comment]
And mopidy/mopidy#1174 for replacements for most of what you use.

**Comment by tkem** [comment]
AFAICS, the only thing missing us `mopidy.utils.path.get_or_create_dir`. IIRC, there was discussion about adding functionality for extensions to create "private" data directories, but I'm not sure about the status of this

**Comment by tkem** [comment]
Used in https://github.com/tkem/mopidy-local-sqlite/blob/master/mopidy_local_sqlite/__init__.py#L48

**Comment by tkem** [comment]
However, I guess thisd can simply be reverted to https://github.com/tkem/mopidy-local-sqlite/blob/v0.8.0/mopidy_local_sqlite/__init__.py#L54
Would still be nice to have the functionality to create private dirs under the Mopidy data_Dir.

**Comment by adamcik** [comment]
Ties in to https://github.com/mopidy/mopidy/issues/843 - I've been wondering if the API there should be something like asking core for a DATA/CACHE/CONFIG dir and then we create it and return the path.

**Comment by tkem** [comment]
I think something along these lines would be really helpful; maybe adding this to `Extension` as a class method and using the `ext_name` implicitly might make sense, too, e.g.
`Extension.get_data_dir(cls)` -> get or create `$XDG_DATA_DIR/mopidy/<cls.ext_name>` and return path?

**Comment by adamcik** [comment]
That was pretty much what I had in mind :-)
