### ISSUE TITLE
Directories showing up empty after successful scan

### ISSUE THREAD

**Issue by jcass77** [tkem/mopidy-local-sqlite#62]
Nothing is showing up in the local media backend when using a web client to access Mopidy, even after running ```mopidy local scan``` successfully.

It seems that the ```library.db``` file is now being written to ```data_dir/images``` instead of ```data_dir/sqlite``` as in previous releases?

Based on the following log output, I suspect that the database is inadvertently deleted by https://github.com/tkem/mopidy-local-images/blob/befc8274e94b990faa2ef729dd77d2f7bdffc667/mopidy_local_images/library.py#L158-171

INFO     Removing 0 missing tracks.
INFO     Found 0 tracks which need to be updated.
INFO     Scanning...
INFO     Scanned 0 of 0 files in 0s.
INFO     Cleaning up image directory
**INFO     Deleting file /var/lib/mopidy/localdata/images/library.db**
INFO     Done scanning.

I'm using Mopidy-Local-Images (0.3.3) and Mopidy-Local-SQLite (0.10.1).

**Comment by tkem** [comment]
Thanks for reporting. Will be fixed ASAP.

**Comment by tkem** [comment]
Pleas try updating Mopidy-Local-SQLite to v0.10.2.
